### ISSUE TITLE
Les tests de feature deadlock au moment du DatabaseCleaner.clean

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4293]
Régulièrement (et aléatoirement) les tests de feature deadlockent à la fin.

Par exemple :

```
  1) As an administrateur I wanna create a new procedure Right after sign_in I shall see all procedure states links Finding archived procedures
     Failure/Error: DS_NB_DEMARCHES_ARCHIVES: current_administrateur&.procedures&.archivees&.count
     
     ActiveRecord::Deadlocked:
       PG::TRDeadlockDetected: ERROR:  deadlock detected
       LINE 1: SELECT COUNT(*) FROM "procedures" INNER JOIN "administrateur...
                                                            ^
       DETAIL:  Process 560 waits for AccessShareLock on relation 16455 of database 16384; blocked by process 360.
       Process 360 waits for AccessExclusiveLock on relation 16862 of database 16384; blocked by process 560.
       HINT:  See server log for query details.
       : SELECT COUNT(*) FROM "procedures" INNER JOIN "administrateurs_procedures" ON "procedures"."id" = "administrateurs_procedures"."procedure_id" WHERE "procedures"."hidden_at" IS NULL AND "administrateurs_procedures"."administrateur_id" = $1 AND "procedures"."aasm_state" = $2
     # ./app/controllers/application_controller.rb:286:in `crisp_config'
     # ./app/controllers/application_controller.rb:127:in `setup_tracking'
     # ------------------
     # --- Caused by: ---
     # PG::TRDeadlockDetected:
     #   ERROR:  deadlock detected
     #   LINE 1: SELECT COUNT(*) FROM "procedures" INNER JOIN "administrateur...
     #                                                        ^
     #   DETAIL:  Process 560 waits for AccessShareLock on relation 16455 of database 16384; blocked by process 360.
     #   Process 360 waits for AccessExclusiveLock on relation 16862 of database 16384; blocked by process 560.
     #   HINT:  See server log for query details.
     #   ./app/controllers/application_controller.rb:286:in `crisp_config'
```

D'après les internets, c'est sans doute parce que la page chargée dans Capybara [fait des requêtes ajax en arrière-plan](https://github.com/teamcapybara/capybara/issues/1089) (indépendamment du test). Du coup le test se termine, mais y'a encore des requêtes qui maintiennent le serveur actif. Et donc ça deadlocke.

Y'a également [quelques infos sur ce problème](https://www.rubydoc.info/gems/database_cleaner#RSpec_with_Capybara_Example) dans la doc de DatabaseCleaner.

Si c'est ça, y'a plusieurs solutions :

1. Compter les requêtes AJAX, et attendre à la fin de chaque test que tout soit fini. Mais ça veut dire qu'il faut instrumenter toutes les libs JS (fragile); et aussi c'est lent.
2. Insérer un middleware Rack qui peut [compter et bloquer les requêtes](https://www.salsify.com/blog/engineering/tearing-capybara-ajax-tests). C'est propre, mais c'est beaucoup de code pour ça.
3. Réessayer de cleanup un certain nombre de fois avant d'abandonner. C'est peu de code, mais peut-être pas 100% efficace.

**Comment by kemenaran** [comment]
3. serait clairement le plus simple.

Le souci, en revanche, c'est que le code qui deadlock peut être non pas dans le cleanup, mais dans la requête concurrente (comme dans l'exemple ci-dessus). Et dans ce cas, wrapper le cleanup dans un _retry_ n'arrangera rien.

**Comment by kemenaran** [comment]
On n'a pas eu le problème depuis longtemps : c'est sans doute que le correctif dans #4294 a fonctionné.
