### ISSUE TITLE
Un feature-test sur les types de champ échoue aléatoirement

### ISSUE THREAD

**Issue by kemenaran** [betagouv/demarches-simplifiees.fr#4417]
https://circleci.com/gh/betagouv/demarches-simplifiees.fr/15759

```
  1) As an administrateur I can edit types de champ Add a new champ
     Failure/Error: fill_in 'champ-0-libelle', with: 'libellé de champ'
     
     Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching field "champ-0-libelle" that is not disabled
     # ./spec/features/new_administrateur/types_de_champ_spec.rb:21:in `block (2 levels) in <top (required)>'

Top 10 slowest examples (49.63 seconds, 42.2% of total time):
  As an administrateur I can edit types de champ Add a new champ
    22.63 seconds ./spec/features/new_administrateur/types_de_champ_spec.rb:12
  Changing an email is easy
    11.65 seconds ./spec/features/users/change_email_spec.rb:11
  As an administrateur I can edit types de champ Add multiple champs
    2.78 seconds ./spec/features/new_administrateur/types_de_champ_spec.rb:33
  As an administrateur I can edit types de champ Add repetition champ
    2.34 seconds ./spec/features/new_administrateur/types_de_champ_spec.rb:96
  As an administrateur I wanna clone a procedure Cloning a procedure owned by the current admin should eq "0"
    2.17 seconds ./spec/features/admin/procedure_cloning_spec.rb:19
  As an administrateur I can edit types de champ Add carte champ
    2.03 seconds ./spec/features/new_administrateur/types_de_champ_spec.rb:126
  Invitations when the dossier is en_construction on dossier details, the owner of a dossier can invite another user to collaborate on the dossier
    1.6 seconds ./spec/features/users/invite_spec.rb:74
  As an administrateur I can edit types de champ Add dropdown champ
    1.55 seconds ./spec/features/new_administrateur/types_de_champ_spec.rb:142
  Invitations when the dossier is a brouillon on the form, the owner of a dossier can invite another user to collaborate on the dossier
    1.47 seconds ./spec/features/users/invite_spec.rb:13
  As an administrateur I can edit types de champ Remove champs
    1.4 seconds ./spec/features/new_administrateur/types_de_champ_spec.rb:69
```

**Comment by kemenaran** [comment]
Ça se produit encore – et je reproduis parfois en local. J'essaie de comprendre ce qui se passe, mais en gros ça a l'air d'être un souci de timing avec l'éditeur de champs.

@tchak si tu as une idée de ce qui se passe…

**Comment by kemenaran** [comment]
Après le downgrade de Capybara, ça échoue aléatoirement sur un autre test de la même spec :

```
Failures:

  1) As an administrateur I can edit types de champ Add multiple champs
     Failure/Error: expect(page).to have_selector('#champ-3-libelle')
       expected to find css "#champ-3-libelle" but there were no matches
     # ./spec/features/new_administrateur/types_de_champ_spec.rb:49:in `block (2 levels) in <top (required)>'

```

**Comment by kemenaran** [comment]
Ce test continue à échouer aléatoirement assez souvent.

**Comment by kemenaran** [comment]
Corrigé par #4577
