### ISSUE TITLE
ETQ Ops, je souhaite désactiver l'affichage des boutons France-Connect

### ISSUE THREAD

**Issue by dzc34** [betagouv/demarches-simplifiees.fr#5440]
##  Actuellement

Lorsqu'on installe sa propre instance DS (par exemple celle de l'_Adullact_) et si on ne configure pas les variables d'environnements relatives à  **FranceConnect**, alors :
- les boutons **FranceConnect** sont visibles 
  - sur la page `/users/sign_in` 
  - sur les pages `/commencer/une-demarche-exemple` quand l'utilisateur n'est pas connecté
- l'URL de ces boutons provoque une erreur 500 "Internal Server Error" :
  - `/france_connect/particulier` à partir de la page `/users/sign_in` 
  - `/commencer/une-demarche-exemple/france_connect` à partir de la page `/commencer/une-demarche-exemple`

```ruby
Started GET "/france_connect/particulier" 
Processing by FranceConnect::ParticulierController#login as HTML
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms | Allocations: 3840)

    'identifier' required. excluded from capture: DSN not set
    AttrRequired::AttrMissing ('identifier' required.):
  
    app/models/france_connect_particulier_client.rb:3:in `initialize'
    app/services/france_connect_service.rb:3:in `new'
    app/services/france_connect_service.rb:3:in `authorization_uri'
    app/controllers/france_connect/particulier_controller.rb:6:in `login'
```

## Comportement attendu

Si on ne configure pas les variables d'environnements relatives à  **FranceConnect** ou si une variable d'environnement complémentaire pour désactiver **FranceConnect** est utilisée alors :
- les boutons **FranceConnect** ne sont plus visibles 
- l'URL `/france_connect/particulier`  redirige vers la page `/users/sign_in` 

--------------
Une PR est dans les tuyaux en utilisant le fichier [config/env.example.optional](https://github.com/betagouv/demarches-simplifiees.fr/blob/dev/config/env.example.optional) pour ajouter une variable d'environnement optionnelle pour désactiver **FranceConnect**

**Comment by dzc34** [comment]
PR #5441
